using System;
using UnityEngine;

/// <summary>
/// This class contains the relevant information for an item to be sold at the pawn shop.
/// Instances of this class are generated by AI, which gives us a JSON representation of this class which we convert into a class instance.
/// </summary>
[Serializable]
public class Item
{
    [SerializeField]
    private string name, description, effect;

    [SerializeField]
    private float marketValue, clientOffer;

    public string Name { get => name; private set => name = value; }
    public string Description { get => description; private set => description = value; }
    public string Effect { get => effect; private set => effect = value; }
    public float MarketValue { get => marketValue; private set => marketValue = value; }
    public float ClientOffer { get => clientOffer; private set => clientOffer = value; }
}
